// Generated by CoffeeScript 1.9.1
(function() {
  describe('Spinclient', function() {
    var spinclient;
    console.log('testing started');
    spinclient = void 0;
    beforeEach(module('ngSpinclient'));
    beforeEach(inject(function(_spinclient_) {
      return spinclient = _spinclient_;
    }));
    return describe('Constructor', function() {
      return it('should work', function() {
        return expect({
          foo: 'bar'
        }).to.have.property('foo', 'bar');
      });
    });
  });

}).call(this);

//# sourceMappingURL=spinclient-spec.js.map
