// Generated by CoffeeScript 1.8.0
(function() {
  describe('Spinclient', function() {
    var server, spinclient;
    console.log('testing started');
    spinclient = void 0;
    server = void 0;
    beforeEach(module('ngSpinclient', 'MockServer'));
    beforeEach(inject(function(_spinclient_, mockserver) {
      spinclient = _spinclient_;
      server = mockserver;
      return spinclient.setWebSocketInstance(server);
    }));
    return describe('Constructor', function() {
      it('should work', function() {
        return expect(server.emit).to.be.a('function');
      });
      return it('should be able to register an object subscriber', function() {
        spinclient.registerObjectSubscriber({
          id: 1,
          type: 'Foo',
          cb: function(obj) {
            console.log('object update');
            return console.dir(obj);
          }
        }).then(function(sid) {
          return console.log('sid is ' + sid);
        });
        return expect(server.emit).to.be.a('function');
      });
    });
  });

}).call(this);

//# sourceMappingURL=spinclient-spec.js.map
